Repository SteamDeckHomebrew/decky-loader, pull requests merged in 2022-10, with the labels that each got.

#190 Change 'PluginLoader' to 'Decky Loader' in readme
  README.md
Labels: documentation, enhancement

#196 Add plugin description to Store PluginCard
  frontend/src/components/store/PluginCard.tsx
Labels: enhancement

#208 README: password typing clarification
  README.md
Labels: enhancement

#212 Use a conditional while loop for when the scroll root is not found.
  frontend/src/tabs-hook.ts
Labels: bug

#214 README rewrite
  README.md
  docs/images/dark/gear.svg
  docs/images/dark/plug.svg
  docs/images/dark/qam.svg
  docs/images/dark/steam.svg
  docs/images/dark/store.svg
  docs/images/dark/x.svg
  docs/images/light/gear.svg
  docs/images/light/plug.svg
  docs/images/light/qam.svg
  docs/images/light/steam.svg
  docs/images/light/store.svg
  docs/images/light/x.svg
Labels: documentation

#217 Rewrite toaster hook to not re-create the window
  frontend/src/components/Toast.tsx
  frontend/src/toaster.tsx
Labels: bug

#211 Developer menu
  backend/injector.py
  backend/utilities.py
  frontend/src/components/Toast.tsx
  frontend/src/components/settings/index.tsx
  frontend/src/components/settings/pages/developer/index.tsx
  frontend/src/components/settings/pages/general/index.tsx
  frontend/src/developer.tsx
  frontend/src/index.tsx
  frontend/src/plugin-loader.tsx
  frontend/src/toaster.tsx
  frontend/src/utils/hooks/useSetting.ts
  frontend/src/utils/settings.ts
Labels: enhancement

#223 During update, download updates first before removing old plugin files
  backend/browser.py
  backend/updater.py
  frontend/src/components/settings/pages/general/index.tsx
Labels: enhancement

#239 Add timeout to get tabs request, wait for network online target before booting decky
  backend/injector.py
  dist/install_prerelease.sh
  dist/install_release.sh
Labels: enhancement

#238 Merge Tabs and Injection Fixes, bring back native Valve toaster
  backend/loader.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/QuickAccessVisibleState.tsx
  frontend/src/components/Toast.tsx
  frontend/src/plugin-loader.tsx
  frontend/src/tabs-hook.old.tsx
  frontend/src/tabs-hook.tsx
  frontend/src/toaster.tsx
Labels: bug

#240 Systemd service updating
  backend/updater.py
  dist/install_prerelease.sh
  dist/install_release.sh
  dist/plugin_loader-prerelease.service
  dist/plugin_loader-release.service
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/settings/pages/general/BranchSelect.tsx
  frontend/src/store.tsx
  frontend/src/tabs-hook.tsx
  frontend/src/updater.ts
Labels: enhancement
