Repository SteamDeckHomebrew/decky-loader, pull requests merged in 2022-09, with the labels that each got.

#168 Addition of proper branch slection
  backend/updater.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/DeckyState.tsx
  frontend/src/components/settings/pages/general/BranchSelect.tsx
  frontend/src/components/settings/pages/general/Updater.tsx
  frontend/src/components/settings/pages/general/index.tsx
  frontend/src/plugin-loader.tsx
  frontend/src/utils/hooks/useSetting.ts
Labels: enhancement

#180 updated installation steps
  README.md
Labels: question

#184 (readme) Make store link go to beta.deckbrew + Change wording
  README.md
Labels: enhancement

#185 fix(pluginview): align icon and plugin name
  frontend/src/components/PluginView.tsx
Labels: enhancement, on-hold
