Repository SteamDeckHomebrew/decky-loader, pull requests merged in 2023-01, with the labels that each got.

#297 User Friendlier Installer
  dist/decky_installer.desktop
  dist/user_install_script.sh
Labels: enhancement

#318 Add feature requests as an issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#342 [readme] change terminal commands to point at decky-installer
  README.md
Labels: enhancement

#341 Aa/bump dfl navigation fix jan2023
  backend/injector.py
  backend/main.py
  backend/utilities.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/index.tsx
Labels: enhancement

#305 Updated store CSS
  frontend/src/components/store/PluginCard.tsx
Labels: enhancement, question

#343 Store and plugin installation visual improvements
  frontend/assets/plugin_store.png
  frontend/index.d.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/rollup.config.js
  frontend/src/components/modals/PluginInstallModal.tsx
  frontend/src/components/store/PluginCard.tsx
  frontend/src/components/store/Store.tsx
  frontend/src/plugin-loader.tsx
  frontend/tsconfig.json
Labels: enhancement

#352 Fix http_request and fetchNoCors methods erroring when including a body.
  frontend/src/plugin-loader.tsx
Labels: feature request

#349 Expose useful env vars to plugin processes
  backend/helpers.py
  backend/main.py
  backend/plugin.py
  backend/settings.py
  backend/updater.py
Labels: enhancement, requires documentation
