Repository SteamDeckHomebrew/decky-loader, pull requests merged in 2023-03, with the labels that each got.

#388 Fix QAM And Toaster Injection for Mar 02 Beta
  backend/updater.py
  frontend/src/tabs-hook.tsx
  frontend/src/toaster.tsx
Labels: bug, enhancement

#391 fix #390 the plugin_directory argument to import_plugin was incorrect
  backend/browser.py
Labels: enhancement, help wanted

#389 Expose USER_ID and DECKY_USER_ID to plugins
  backend/plugin.py
  plugin/decky_plugin.py
  plugin/decky_plugin.pyi
Labels: enhancement

#395 Shared Ctx tab rename to SharedJSContext
  backend/injector.py
Labels: bug, enhancement

#387 Add cross-platform support to decky
  .github/workflows/build.yml
  backend/browser.py
  backend/customtypes.py
  backend/helpers.py
  backend/loader.py
  backend/localplatform.py
  backend/localplatformlinux.py
  backend/localplatformwin.py
  backend/localsocket.py
  backend/main.py
  backend/plugin.py
  backend/settings.py
  backend/updater.py
  backend/utilities.py
Labels: enhancement
