Repository SteamDeckHomebrew/decky-loader, pull requests merged in 2024-08, with the labels that each got.

#664 fix: fetchNoCors and http_request data handling
  backend/decky_loader/utilities.py
  frontend/src/plugin-loader.tsx
Labels: enhancement

#661 Rewrite router/tabs/toaster hooks
  backend/decky_loader/injector.py
  backend/decky_loader/main.py
  backend/decky_loader/utilities.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/DeckyIcon.tsx
  frontend/src/components/DeckyToaster.tsx
  frontend/src/components/DeckyToasterState.tsx
  frontend/src/components/TitleView.tsx
  frontend/src/components/Toast.tsx
  frontend/src/components/modals/filepicker/patches/index.ts
  frontend/src/components/settings/pages/testing/index.tsx
  frontend/src/errorboundary-hook.tsx
  frontend/src/index.ts
  frontend/src/plugin-loader.tsx
  frontend/src/router-hook.tsx
  frontend/src/tabs-hook.tsx
  frontend/src/toaster.tsx
Labels: enhancement, javascript

#668 Work around account switching failing to open the CEF debugger socket
  backend/decky_loader/localplatform/localplatform.py
  backend/decky_loader/localplatform/localplatformlinux.py
  backend/decky_loader/localplatform/localplatformwin.py
  backend/decky_loader/utilities.py
  frontend/src/steamfixes/index.ts
  frontend/src/steamfixes/socket.ts
Labels: javascript, python
